language: crystal
os:
- linux
- osx
env:
  NAME: hello-travis
  LDFLAGS: -L/usr/local/opt/openssl/lib
script:
- crystal tool format --check
- shards install
- shards build "$NAME" --release --error-trace -s -p -t
- mv -f -v "bin/${NAME}" "bin/${NAME}-${TRAVIS_OS_NAME}"
- bin/${NAME}-${TRAVIS_OS_NAME}
deploy:
  provider: releases
  api_key:
    secure: cFrx9s62w51XdiSsww4OtjSp6+IR/iIqVYyC6arydtLBWkZ8tmJ6gPZB+DsOHJZ9C4gXImprLZsBfjeLyZ5kBX3a5TcD0ONykv3rF2XEtOcfh9ru6pOfW1I2B1r4ULH39G4XGjmABQlnt5gmDPXIl0h7vDxXvRraSAwqmH5RYfRHbuUkCiYBazGRvrr87HTyCjKJ59l33Kv180cbly6OovOJH7Xzc1Ff6hNFgb/suWtRHxCj8i0uT7pCACeXH8IAZOLTLtwIaiqKaXcDQxQdBZnANA/XZGLKkMYfxfEtZp8bOKr+PS7ywOzlN+BpJv+YJhfG3lb+dV1VeZ0U07ASTya4923hPQAfw/gc0fY6636uWZJSV6LG6TlCHX1xJyMeqsP70ZMECWNdq6Z6INWPph/2aiK3AVa9tnmz8fwu6zXKUd9GE/HSsI91g+3bcqT4n1g/F0Xh9weepAx0lSIvcjmy9NIwZ4Kn6a217ZMcC2Dm43SMmD/+mvfdfF66CkgzgSYZOnqwflGJjMO+BCq6AmLkjRFcc2J0fTUPoGLV6M4hxm+3quJV2RI02wr8LOTrxwAlqO/j0YDcelk7IKPxlxiWqZqMSY9y+p/poR+BAZA0p14y9Rg+eivFwMDDE6LR2fVY4DzJ6XQIbL4O3eFyM+R4EEcPShMVB42YpR4GSm4=
  file: "bin/${NAME}-${TRAVIS_OS_NAME}"
  on:
    repo: plambert/hello-travis.cr
  skip_cleanup: 'true'
